# Generated by Django 5.0.4 on 2024-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
