# Generated by Django 5.0.4 on 2024-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_city_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
